package DAVSClient;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DAVS_About.java
 *
 * Created on Feb 15, 2009, 3:19:31 PM
 */

/**
 *
 * @author waqasdaar
 */
public class DAVS_About extends javax.swing.JDialog {

    /** Creates new form DAVS_About */
    public DAVS_About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(Close_Botton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        About_Text = new javax.swing.JLabel();
        Version = new javax.swing.JLabel();
        Version_Number = new javax.swing.JLabel();
        Product = new javax.swing.JLabel();
        Product_Name = new javax.swing.JLabel();
        Close_Botton = new javax.swing.JButton();
        Lable_Author = new javax.swing.JLabel();
        Author = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DAVS About");
        setName("About"); // NOI18N
        setResizable(false);

        About_Text.setText("<html>This is distribution agnostic video client,which  is used to play  media files and  provides the distribution agnostic functionality."); // NOI18N
        About_Text.setName("About_Text"); // NOI18N

        Version.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Version.setText("Version");
        Version.setName("Version"); // NOI18N

        Version_Number.setText("0.1");
        Version_Number.setName("Version_Number"); // NOI18N

        Product.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Product.setText("Product");
        Product.setName("Product"); // NOI18N

        Product_Name.setText("Distribution agnostic video server client");
        Product_Name.setName("Product_Name"); // NOI18N

        Close_Botton.setText("Close");
        Close_Botton.setName("Close_Botton"); // NOI18N
        Close_Botton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_BottonMouseClicked(evt);
            }
        });

        Lable_Author.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Lable_Author.setText("Author");
        Lable_Author.setName("Lable_Author"); // NOI18N

        Author.setText("Waqas Daar");
        Author.setName("Author"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(DAVS_About.class);
        jLabel1.setIcon(resourceMap.getIcon("davs.icon")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(About_Text, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Product)
                            .add(Version)
                            .add(Lable_Author))
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Author)
                            .add(Version_Number)
                            .add(Product_Name))))
                .add(26, 26, 26))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .add(Close_Botton)
                .add(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(About_Text)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Product)
                            .add(Product_Name))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Version)
                            .add(Version_Number))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Lable_Author)
                            .add(Author))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(Close_Botton)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("DAVS_Image");

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Close_BottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_BottonMouseClicked
        dispose();
    }//GEN-LAST:event_Close_BottonMouseClicked

       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About_Text;
    private javax.swing.JLabel Author;
    private javax.swing.JButton Close_Botton;
    private javax.swing.JLabel Lable_Author;
    private javax.swing.JLabel Product;
    private javax.swing.JLabel Product_Name;
    private javax.swing.JLabel Version;
    private javax.swing.JLabel Version_Number;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
