/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "davs.h"


void
davs_10(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *davs_rtsp_validate_10_arg1;
	int davs_rtsp_validate_10_arg2;
	int  *result_2;
	char *davs_rtsp_stop_10_arg1;
	int  *result_3;
	char *davs_rtsp_deport_10_arg1;
	int  *result_4;
	char *davs_rtsp_vod_10_arg1;
	char *davs_rtsp_vod_10_arg2;
	char *davs_rtsp_vod_10_arg3;
	char *davs_rtsp_vod_10_arg4;
	char *davs_rtsp_vod_10_arg5;
	int  *result_5;
	char *davs_rtsp_broadcast_10_arg1;
	char *davs_rtsp_broadcast_10_arg2;
	int  *result_6;
	char *davs_rtsp_removevodstream_10_arg1;
	int  *result_7;
	char *davs_rtsp_removelivestream_10_arg1;
	int  *result_8;
	char *davs_p2p_validate_10_arg1;
	int  *result_9;
	char *davs_p2p_start_10_arg1;
	int  *result_10;
	char *davs_p2p_stop_10_arg1;
	char *davs_p2p_stop_10_arg2;
	int  *result_11;
	char *davs_live555_validate_10_arg1;
	int davs_live555_validate_10_arg2;
	int  *result_12;
	char *davs_streamavailable_10_arg1;
	char * *result_13;
	char * *result_14;
	char * *result_15;
	char * *result_16;
	char *davs_getvodstream_description_10_arg1;
	char * *result_17;
	char *davs_getbroadcaststream_description_10_arg1;
	char * *result_18;
	char *davs_getsnapshot_10_arg1;
	char * *result_19;
	char *davs_getstreamuri_10_arg1;
	ScriptResult  *result_20;
	char *davs_p2p_import_10_arg1;
	int davs_p2p_import_10_arg2;
	char *davs_p2p_import_10_arg3;
	char *davs_p2p_import_10_arg4;
	ScriptResult  *result_21;
	char *davs_p2p_play_10_arg1;
	ScriptResult  *result_22;
	int davs_live555_import_10_arg1;
	char *davs_live555_import_10_arg2;
	int davs_live555_import_10_arg3;
	char *davs_live555_import_10_arg4;
	char *davs_live555_import_10_arg5;
	ScriptResult  *result_23;
	int davs_rtsp_import_10_arg1;
	char *davs_rtsp_import_10_arg2;
	int davs_rtsp_import_10_arg3;
	char *davs_rtsp_import_10_arg4;
	char *davs_rtsp_import_10_arg5;
	ScriptResult  *result_24;
	char *davs_rtsp_start_10_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, DAVS, DAVS_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = davs_rtsp_validate_10(davs_rtsp_validate_10_arg1, davs_rtsp_validate_10_arg2, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = davs_rtsp_stop_10(davs_rtsp_stop_10_arg1, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = davs_rtsp_deport_10(davs_rtsp_deport_10_arg1, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = davs_rtsp_vod_10(davs_rtsp_vod_10_arg1, davs_rtsp_vod_10_arg2, davs_rtsp_vod_10_arg3, davs_rtsp_vod_10_arg4, davs_rtsp_vod_10_arg5, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = davs_rtsp_broadcast_10(davs_rtsp_broadcast_10_arg1, davs_rtsp_broadcast_10_arg2, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = davs_rtsp_removevodstream_10(davs_rtsp_removevodstream_10_arg1, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = davs_rtsp_removelivestream_10(davs_rtsp_removelivestream_10_arg1, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = davs_p2p_validate_10(davs_p2p_validate_10_arg1, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = davs_p2p_start_10(davs_p2p_start_10_arg1, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = davs_p2p_stop_10(davs_p2p_stop_10_arg1, davs_p2p_stop_10_arg2, clnt);
	if (result_10 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = davs_live555_validate_10(davs_live555_validate_10_arg1, davs_live555_validate_10_arg2, clnt);
	if (result_11 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = davs_streamavailable_10(davs_streamavailable_10_arg1, clnt);
	if (result_12 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = davs_getstreamingengines_10(clnt);
	if (result_13 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_14 = davs_getvodstreams_10(clnt);
	if (result_14 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_15 = davs_getbroadcast_streams_10(clnt);
	if (result_15 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_16 = davs_getvodstream_description_10(davs_getvodstream_description_10_arg1, clnt);
	if (result_16 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_17 = davs_getbroadcaststream_description_10(davs_getbroadcaststream_description_10_arg1, clnt);
	if (result_17 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_18 = davs_getsnapshot_10(davs_getsnapshot_10_arg1, clnt);
	if (result_18 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_19 = davs_getstreamuri_10(davs_getstreamuri_10_arg1, clnt);
	if (result_19 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_20 = davs_p2p_import_10(davs_p2p_import_10_arg1, davs_p2p_import_10_arg2, davs_p2p_import_10_arg3, davs_p2p_import_10_arg4, clnt);
	if (result_20 == (ScriptResult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_21 = davs_p2p_play_10(davs_p2p_play_10_arg1, clnt);
	if (result_21 == (ScriptResult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_22 = davs_live555_import_10(davs_live555_import_10_arg1, davs_live555_import_10_arg2, davs_live555_import_10_arg3, davs_live555_import_10_arg4, davs_live555_import_10_arg5, clnt);
	if (result_22 == (ScriptResult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_23 = davs_rtsp_import_10(davs_rtsp_import_10_arg1, davs_rtsp_import_10_arg2, davs_rtsp_import_10_arg3, davs_rtsp_import_10_arg4, davs_rtsp_import_10_arg5, clnt);
	if (result_23 == (ScriptResult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_24 = davs_rtsp_start_10(davs_rtsp_start_10_arg1, clnt);
	if (result_24 == (ScriptResult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	davs_10 (host);
exit (0);
}
