/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DAVS_H_RPCGEN
#define _DAVS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define Command_MAX 1024

struct ScriptResult {
	int ExitStatus;
	char CommandOutPut[Command_MAX];
};
typedef struct ScriptResult ScriptResult;

struct davs_rtsp_validate_10_argument {
	char *arg1;
	int arg2;
};
typedef struct davs_rtsp_validate_10_argument davs_rtsp_validate_10_argument;

struct davs_rtsp_vod_10_argument {
	char *arg1;
	char *arg2;
	char *arg3;
	char *arg4;
	char *arg5;
};
typedef struct davs_rtsp_vod_10_argument davs_rtsp_vod_10_argument;

struct davs_rtsp_broadcast_10_argument {
	char *arg1;
	char *arg2;
};
typedef struct davs_rtsp_broadcast_10_argument davs_rtsp_broadcast_10_argument;

struct davs_p2p_stop_10_argument {
	char *arg1;
	char *arg2;
};
typedef struct davs_p2p_stop_10_argument davs_p2p_stop_10_argument;

struct davs_live555_validate_10_argument {
	char *arg1;
	int arg2;
};
typedef struct davs_live555_validate_10_argument davs_live555_validate_10_argument;

struct davs_p2p_import_10_argument {
	char *arg1;
	int arg2;
	char *arg3;
	char *arg4;
};
typedef struct davs_p2p_import_10_argument davs_p2p_import_10_argument;

struct davs_live555_import_10_argument {
	int arg1;
	char *arg2;
	int arg3;
	char *arg4;
	char *arg5;
};
typedef struct davs_live555_import_10_argument davs_live555_import_10_argument;

struct davs_rtsp_import_10_argument {
	int arg1;
	char *arg2;
	int arg3;
	char *arg4;
	char *arg5;
};
typedef struct davs_rtsp_import_10_argument davs_rtsp_import_10_argument;

#define DAVS 0x20001234
#define DAVS_VERSION 10

#if defined(__STDC__) || defined(__cplusplus)
#define davs_rtsp_validate 1
extern  int * davs_rtsp_validate_10(char *, int , CLIENT *);
extern  int * davs_rtsp_validate_10_svc(char *, int , struct svc_req *);
#define davs_rtsp_stop 4
extern  int * davs_rtsp_stop_10(char *, CLIENT *);
extern  int * davs_rtsp_stop_10_svc(char *, struct svc_req *);
#define davs_rtsp_deport 5
extern  int * davs_rtsp_deport_10(char *, CLIENT *);
extern  int * davs_rtsp_deport_10_svc(char *, struct svc_req *);
#define davs_rtsp_vod 10
extern  int * davs_rtsp_vod_10(char *, char *, char *, char *, char *, CLIENT *);
extern  int * davs_rtsp_vod_10_svc(char *, char *, char *, char *, char *, struct svc_req *);
#define davs_rtsp_broadcast 11
extern  int * davs_rtsp_broadcast_10(char *, char *, CLIENT *);
extern  int * davs_rtsp_broadcast_10_svc(char *, char *, struct svc_req *);
#define davs_rtsp_RemoveVODStream 14
extern  int * davs_rtsp_removevodstream_10(char *, CLIENT *);
extern  int * davs_rtsp_removevodstream_10_svc(char *, struct svc_req *);
#define davs_rtsp_RemoveLiveStream 15
extern  int * davs_rtsp_removelivestream_10(char *, CLIENT *);
extern  int * davs_rtsp_removelivestream_10_svc(char *, struct svc_req *);
#define davs_p2p_validate 20
extern  int * davs_p2p_validate_10(char *, CLIENT *);
extern  int * davs_p2p_validate_10_svc(char *, struct svc_req *);
#define davs_p2p_start 23
extern  int * davs_p2p_start_10(char *, CLIENT *);
extern  int * davs_p2p_start_10_svc(char *, struct svc_req *);
#define davs_p2p_stop 24
extern  int * davs_p2p_stop_10(char *, char *, CLIENT *);
extern  int * davs_p2p_stop_10_svc(char *, char *, struct svc_req *);
#define davs_live555_validate 16
extern  int * davs_live555_validate_10(char *, int , CLIENT *);
extern  int * davs_live555_validate_10_svc(char *, int , struct svc_req *);
#define davs_streamavailable 25
extern  int * davs_streamavailable_10(char *, CLIENT *);
extern  int * davs_streamavailable_10_svc(char *, struct svc_req *);
#define davs_GetStreamingEngines 13
extern  char ** davs_getstreamingengines_10(CLIENT *);
extern  char ** davs_getstreamingengines_10_svc(struct svc_req *);
#define davs_GetVodStreams 6
extern  char ** davs_getvodstreams_10(CLIENT *);
extern  char ** davs_getvodstreams_10_svc(struct svc_req *);
#define davs_GetBroadcast_Streams 7
extern  char ** davs_getbroadcast_streams_10(CLIENT *);
extern  char ** davs_getbroadcast_streams_10_svc(struct svc_req *);
#define davs_GetVodStream_Description 8
extern  char ** davs_getvodstream_description_10(char *, CLIENT *);
extern  char ** davs_getvodstream_description_10_svc(char *, struct svc_req *);
#define davs_GetBroadcastStream_Description 9
extern  char ** davs_getbroadcaststream_description_10(char *, CLIENT *);
extern  char ** davs_getbroadcaststream_description_10_svc(char *, struct svc_req *);
#define davs_GetSnapshot 12
extern  char ** davs_getsnapshot_10(char *, CLIENT *);
extern  char ** davs_getsnapshot_10_svc(char *, struct svc_req *);
#define davs_GetStreamURI 18
extern  char ** davs_getstreamuri_10(char *, CLIENT *);
extern  char ** davs_getstreamuri_10_svc(char *, struct svc_req *);
#define davs_p2p_import 21
extern  ScriptResult * davs_p2p_import_10(char *, int , char *, char *, CLIENT *);
extern  ScriptResult * davs_p2p_import_10_svc(char *, int , char *, char *, struct svc_req *);
#define davs_p2p_play 22
extern  ScriptResult * davs_p2p_play_10(char *, CLIENT *);
extern  ScriptResult * davs_p2p_play_10_svc(char *, struct svc_req *);
#define davs_live555_import 17
extern  ScriptResult * davs_live555_import_10(int , char *, int , char *, char *, CLIENT *);
extern  ScriptResult * davs_live555_import_10_svc(int , char *, int , char *, char *, struct svc_req *);
#define davs_rtsp_import 2
extern  ScriptResult * davs_rtsp_import_10(int , char *, int , char *, char *, CLIENT *);
extern  ScriptResult * davs_rtsp_import_10_svc(int , char *, int , char *, char *, struct svc_req *);
#define davs_rtsp_start 3
extern  ScriptResult * davs_rtsp_start_10(char *, CLIENT *);
extern  ScriptResult * davs_rtsp_start_10_svc(char *, struct svc_req *);
extern int davs_10_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define davs_rtsp_validate 1
extern  int * davs_rtsp_validate_10();
extern  int * davs_rtsp_validate_10_svc();
#define davs_rtsp_stop 4
extern  int * davs_rtsp_stop_10();
extern  int * davs_rtsp_stop_10_svc();
#define davs_rtsp_deport 5
extern  int * davs_rtsp_deport_10();
extern  int * davs_rtsp_deport_10_svc();
#define davs_rtsp_vod 10
extern  int * davs_rtsp_vod_10();
extern  int * davs_rtsp_vod_10_svc();
#define davs_rtsp_broadcast 11
extern  int * davs_rtsp_broadcast_10();
extern  int * davs_rtsp_broadcast_10_svc();
#define davs_rtsp_RemoveVODStream 14
extern  int * davs_rtsp_removevodstream_10();
extern  int * davs_rtsp_removevodstream_10_svc();
#define davs_rtsp_RemoveLiveStream 15
extern  int * davs_rtsp_removelivestream_10();
extern  int * davs_rtsp_removelivestream_10_svc();
#define davs_p2p_validate 20
extern  int * davs_p2p_validate_10();
extern  int * davs_p2p_validate_10_svc();
#define davs_p2p_start 23
extern  int * davs_p2p_start_10();
extern  int * davs_p2p_start_10_svc();
#define davs_p2p_stop 24
extern  int * davs_p2p_stop_10();
extern  int * davs_p2p_stop_10_svc();
#define davs_live555_validate 16
extern  int * davs_live555_validate_10();
extern  int * davs_live555_validate_10_svc();
#define davs_streamavailable 25
extern  int * davs_streamavailable_10();
extern  int * davs_streamavailable_10_svc();
#define davs_GetStreamingEngines 13
extern  char ** davs_getstreamingengines_10();
extern  char ** davs_getstreamingengines_10_svc();
#define davs_GetVodStreams 6
extern  char ** davs_getvodstreams_10();
extern  char ** davs_getvodstreams_10_svc();
#define davs_GetBroadcast_Streams 7
extern  char ** davs_getbroadcast_streams_10();
extern  char ** davs_getbroadcast_streams_10_svc();
#define davs_GetVodStream_Description 8
extern  char ** davs_getvodstream_description_10();
extern  char ** davs_getvodstream_description_10_svc();
#define davs_GetBroadcastStream_Description 9
extern  char ** davs_getbroadcaststream_description_10();
extern  char ** davs_getbroadcaststream_description_10_svc();
#define davs_GetSnapshot 12
extern  char ** davs_getsnapshot_10();
extern  char ** davs_getsnapshot_10_svc();
#define davs_GetStreamURI 18
extern  char ** davs_getstreamuri_10();
extern  char ** davs_getstreamuri_10_svc();
#define davs_p2p_import 21
extern  ScriptResult * davs_p2p_import_10();
extern  ScriptResult * davs_p2p_import_10_svc();
#define davs_p2p_play 22
extern  ScriptResult * davs_p2p_play_10();
extern  ScriptResult * davs_p2p_play_10_svc();
#define davs_live555_import 17
extern  ScriptResult * davs_live555_import_10();
extern  ScriptResult * davs_live555_import_10_svc();
#define davs_rtsp_import 2
extern  ScriptResult * davs_rtsp_import_10();
extern  ScriptResult * davs_rtsp_import_10_svc();
#define davs_rtsp_start 3
extern  ScriptResult * davs_rtsp_start_10();
extern  ScriptResult * davs_rtsp_start_10_svc();
extern int davs_10_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ScriptResult (XDR *, ScriptResult*);
extern  bool_t xdr_davs_rtsp_validate_10_argument (XDR *, davs_rtsp_validate_10_argument*);
extern  bool_t xdr_davs_rtsp_vod_10_argument (XDR *, davs_rtsp_vod_10_argument*);
extern  bool_t xdr_davs_rtsp_broadcast_10_argument (XDR *, davs_rtsp_broadcast_10_argument*);
extern  bool_t xdr_davs_p2p_stop_10_argument (XDR *, davs_p2p_stop_10_argument*);
extern  bool_t xdr_davs_live555_validate_10_argument (XDR *, davs_live555_validate_10_argument*);
extern  bool_t xdr_davs_p2p_import_10_argument (XDR *, davs_p2p_import_10_argument*);
extern  bool_t xdr_davs_live555_import_10_argument (XDR *, davs_live555_import_10_argument*);
extern  bool_t xdr_davs_rtsp_import_10_argument (XDR *, davs_rtsp_import_10_argument*);

#else /* K&R C */
extern bool_t xdr_ScriptResult ();
extern bool_t xdr_davs_rtsp_validate_10_argument ();
extern bool_t xdr_davs_rtsp_vod_10_argument ();
extern bool_t xdr_davs_rtsp_broadcast_10_argument ();
extern bool_t xdr_davs_p2p_stop_10_argument ();
extern bool_t xdr_davs_live555_validate_10_argument ();
extern bool_t xdr_davs_p2p_import_10_argument ();
extern bool_t xdr_davs_live555_import_10_argument ();
extern bool_t xdr_davs_rtsp_import_10_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DAVS_H_RPCGEN */
