/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "davs.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_davs_rtsp_validate_10 (davs_rtsp_validate_10_argument *argp, struct svc_req *rqstp)
{
	return (davs_rtsp_validate_10_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_davs_rtsp_stop_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_rtsp_stop_10_svc(*argp, rqstp));
}

static int *
_davs_rtsp_deport_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_rtsp_deport_10_svc(*argp, rqstp));
}

static int *
_davs_rtsp_vod_10 (davs_rtsp_vod_10_argument *argp, struct svc_req *rqstp)
{
	return (davs_rtsp_vod_10_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, rqstp));
}

static int *
_davs_rtsp_broadcast_10 (davs_rtsp_broadcast_10_argument *argp, struct svc_req *rqstp)
{
	return (davs_rtsp_broadcast_10_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_davs_rtsp_removevodstream_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_rtsp_removevodstream_10_svc(*argp, rqstp));
}

static int *
_davs_rtsp_removelivestream_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_rtsp_removelivestream_10_svc(*argp, rqstp));
}

static int *
_davs_p2p_validate_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_p2p_validate_10_svc(*argp, rqstp));
}

static int *
_davs_p2p_start_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_p2p_start_10_svc(*argp, rqstp));
}

static int *
_davs_p2p_stop_10 (davs_p2p_stop_10_argument *argp, struct svc_req *rqstp)
{
	return (davs_p2p_stop_10_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_davs_live555_validate_10 (davs_live555_validate_10_argument *argp, struct svc_req *rqstp)
{
	return (davs_live555_validate_10_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_davs_streamavailable_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_streamavailable_10_svc(*argp, rqstp));
}

static char **
_davs_getstreamingengines_10 (void  *argp, struct svc_req *rqstp)
{
	return (davs_getstreamingengines_10_svc(rqstp));
}

static char **
_davs_getvodstreams_10 (void  *argp, struct svc_req *rqstp)
{
	return (davs_getvodstreams_10_svc(rqstp));
}

static char **
_davs_getbroadcast_streams_10 (void  *argp, struct svc_req *rqstp)
{
	return (davs_getbroadcast_streams_10_svc(rqstp));
}

static char **
_davs_getvodstream_description_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_getvodstream_description_10_svc(*argp, rqstp));
}

static char **
_davs_getbroadcaststream_description_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_getbroadcaststream_description_10_svc(*argp, rqstp));
}

static char **
_davs_getsnapshot_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_getsnapshot_10_svc(*argp, rqstp));
}

static char **
_davs_getstreamuri_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_getstreamuri_10_svc(*argp, rqstp));
}

static ScriptResult *
_davs_p2p_import_10 (davs_p2p_import_10_argument *argp, struct svc_req *rqstp)
{
	return (davs_p2p_import_10_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, rqstp));
}

static ScriptResult *
_davs_p2p_play_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_p2p_play_10_svc(*argp, rqstp));
}

static ScriptResult *
_davs_live555_import_10 (davs_live555_import_10_argument *argp, struct svc_req *rqstp)
{
	return (davs_live555_import_10_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, rqstp));
}

static ScriptResult *
_davs_rtsp_import_10 (davs_rtsp_import_10_argument *argp, struct svc_req *rqstp)
{
	return (davs_rtsp_import_10_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, rqstp));
}

static ScriptResult *
_davs_rtsp_start_10 (char * *argp, struct svc_req *rqstp)
{
	return (davs_rtsp_start_10_svc(*argp, rqstp));
}

static void
davs_10(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		davs_rtsp_validate_10_argument davs_rtsp_validate_10_arg;
		char *davs_rtsp_stop_10_arg;
		char *davs_rtsp_deport_10_arg;
		davs_rtsp_vod_10_argument davs_rtsp_vod_10_arg;
		davs_rtsp_broadcast_10_argument davs_rtsp_broadcast_10_arg;
		char *davs_rtsp_removevodstream_10_arg;
		char *davs_rtsp_removelivestream_10_arg;
		char *davs_p2p_validate_10_arg;
		char *davs_p2p_start_10_arg;
		davs_p2p_stop_10_argument davs_p2p_stop_10_arg;
		davs_live555_validate_10_argument davs_live555_validate_10_arg;
		char *davs_streamavailable_10_arg;
		char *davs_getvodstream_description_10_arg;
		char *davs_getbroadcaststream_description_10_arg;
		char *davs_getsnapshot_10_arg;
		char *davs_getstreamuri_10_arg;
		davs_p2p_import_10_argument davs_p2p_import_10_arg;
		char *davs_p2p_play_10_arg;
		davs_live555_import_10_argument davs_live555_import_10_arg;
		davs_rtsp_import_10_argument davs_rtsp_import_10_arg;
		char *davs_rtsp_start_10_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case davs_rtsp_validate:
		_xdr_argument = (xdrproc_t) xdr_davs_rtsp_validate_10_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_rtsp_validate_10;
		break;

	case davs_rtsp_stop:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_rtsp_stop_10;
		break;

	case davs_rtsp_deport:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_rtsp_deport_10;
		break;

	case davs_rtsp_vod:
		_xdr_argument = (xdrproc_t) xdr_davs_rtsp_vod_10_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_rtsp_vod_10;
		break;

	case davs_rtsp_broadcast:
		_xdr_argument = (xdrproc_t) xdr_davs_rtsp_broadcast_10_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_rtsp_broadcast_10;
		break;

	case davs_rtsp_RemoveVODStream:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_rtsp_removevodstream_10;
		break;

	case davs_rtsp_RemoveLiveStream:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_rtsp_removelivestream_10;
		break;

	case davs_p2p_validate:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_p2p_validate_10;
		break;

	case davs_p2p_start:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_p2p_start_10;
		break;

	case davs_p2p_stop:
		_xdr_argument = (xdrproc_t) xdr_davs_p2p_stop_10_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_p2p_stop_10;
		break;

	case davs_live555_validate:
		_xdr_argument = (xdrproc_t) xdr_davs_live555_validate_10_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_live555_validate_10;
		break;

	case davs_streamavailable:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _davs_streamavailable_10;
		break;

	case davs_GetStreamingEngines:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _davs_getstreamingengines_10;
		break;

	case davs_GetVodStreams:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _davs_getvodstreams_10;
		break;

	case davs_GetBroadcast_Streams:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _davs_getbroadcast_streams_10;
		break;

	case davs_GetVodStream_Description:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _davs_getvodstream_description_10;
		break;

	case davs_GetBroadcastStream_Description:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _davs_getbroadcaststream_description_10;
		break;

	case davs_GetSnapshot:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _davs_getsnapshot_10;
		break;

	case davs_GetStreamURI:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _davs_getstreamuri_10;
		break;

	case davs_p2p_import:
		_xdr_argument = (xdrproc_t) xdr_davs_p2p_import_10_argument;
		_xdr_result = (xdrproc_t) xdr_ScriptResult;
		local = (char *(*)(char *, struct svc_req *)) _davs_p2p_import_10;
		break;

	case davs_p2p_play:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_ScriptResult;
		local = (char *(*)(char *, struct svc_req *)) _davs_p2p_play_10;
		break;

	case davs_live555_import:
		_xdr_argument = (xdrproc_t) xdr_davs_live555_import_10_argument;
		_xdr_result = (xdrproc_t) xdr_ScriptResult;
		local = (char *(*)(char *, struct svc_req *)) _davs_live555_import_10;
		break;

	case davs_rtsp_import:
		_xdr_argument = (xdrproc_t) xdr_davs_rtsp_import_10_argument;
		_xdr_result = (xdrproc_t) xdr_ScriptResult;
		local = (char *(*)(char *, struct svc_req *)) _davs_rtsp_import_10;
		break;

	case davs_rtsp_start:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_ScriptResult;
		local = (char *(*)(char *, struct svc_req *)) _davs_rtsp_start_10;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DAVS, DAVS_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DAVS, DAVS_VERSION, davs_10, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DAVS, DAVS_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DAVS, DAVS_VERSION, davs_10, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DAVS, DAVS_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
