package DAVSClient;

import DAVSLogin.Login;

/*
 * DAVSLogin.java
 *
 * Created on Apr 8, 2009, 1:32:51 PM
 */



import javax.swing.JOptionPane;

/**
 *
 * @author waqasdaar
 */
public class DAVSLogin extends javax.swing.JDialog {

    /** Creates new form DAVSLogin */
    public DAVSLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        objDAVS = new Login();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Login = new javax.swing.JLabel();
        UserLogin = new javax.swing.JTextField();
        Label_Password = new javax.swing.JLabel();
        UserPassword = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Distribution Agnostic Video Servre");
        setResizable(false);

        Label_Login.setText("Login");
        Label_Login.setName("Label_Login"); // NOI18N

        UserLogin.setName("UserLogin"); // NOI18N

        Label_Password.setText("Password");
        Label_Password.setName("Label_Password"); // NOI18N

        UserPassword.setEchoChar('*');
        UserPassword.setName("UserPassword"); // NOI18N

        Login.setText("Login");
        Login.setName("Login"); // NOI18N
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.setName("Cancel"); // NOI18N
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Password)
                    .addComponent(Label_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(Cancel))
                    .addComponent(UserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap(55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_Login)
                    .addComponent(UserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Password)
                    .addComponent(UserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancel)
                    .addComponent(Login))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked

        if(UserPassword.getPassword().length<6) {
            JOptionPane.showMessageDialog(null,"Please enter the atleaset 6 length character password.",
                    "DAVS Message",JOptionPane.OK_OPTION);
         } else {
            int IsOK=objDAVS.CheckLogin(UserLogin.getText(), UserPassword.getText());
            if(IsOK==0) {
                 String UserRole=objDAVS.GetRole(UserLogin.getText());
                 DAVS_Client.DAVSClientStart(UserRole);
                 this.dispose();
            } else {
              JOptionPane.showMessageDialog(this,"The user name or password is incorrect. Please try again.","DAVS Message",JOptionPane.ERROR_MESSAGE);
            }
         }

    }//GEN-LAST:event_LoginMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
          if(evt.getSource()==Cancel) {
              this.dispose();
              System.exit(0);
          }
    }//GEN-LAST:event_CancelMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DAVSLogin dialog = new DAVSLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Label_Login;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JButton Login;
    private javax.swing.JTextField UserLogin;
    private javax.swing.JPasswordField UserPassword;
    // End of variables declaration//GEN-END:variables
Login objDAVS;

   
}
